### ISSUE TITLE
MP4 & HLS recording corruption after streamer disconnects

### ISSUE THREAD

**Issue by Shadowfaxenator** [livekit/egress#160] opened 2022-10-30 03:34 UTC
I have  issue with LiveKit Cloud.
When a streamer disconnects due to network issue (or other short interrupt) egress still works, but MP4 recording on S3 becomes corrupted after stream is stoped. There is no seamless transition in video and audio, video just stalls.

UPDATE:
it happened only when using `TrackCompositeEgressRequest`,
`RoomCompositeEgressRequest` works correctly 

```
&livekit.TrackCompositeEgressRequest{
	RoomName:     "test-room3",
	AudioTrackId: "TR_AMUeuCNthEmzn7",
	VideoTrackId: "TR_VCVRmHNrygNWWK",
	Output: &livekit.TrackCompositeEgressRequest_File{
		File: &livekit.EncodedFileOutput{
			FileType:        livekit.EncodedFileType_MP4,
			Filepath:        "/test",
			DisableManifest: false,
			Output: &livekit.EncodedFileOutput_S3{
				S3: &livekit.S3Upload{
					AccessKey: "xxx",
					Secret:    "xxx",
					Region:    "ams3",
					Endpoint:  "ams3.digitaloceanspaces.com",
					Bucket:    "xxx",
				},
			},
		},
	},
```

**Comment by frostbyte73** [comment] 2023-03-20 20:00
closing as duplicate of https://github.com/livekit/egress/issues/210. Will provide all updates there

**Closed by frostbyte73** 2023-03-20 20:00 UTC
Labels: bug
