### ISSUE TITLE
How to use GPU in egress?

### ISSUE THREAD

**Issue by Abvgdejg** [livekit/egress#658] opened 2024-04-23 13:52 UTC
We use egress to redirect the RTC stream to RTMP, and this consumes ~800 MB of RAM per stream. We want to use the GPU to avoid using so much RAM.

**Comment by frostbyte73** [comment] 2024-04-23 21:05
Closing as duplicate of #170. 
It would require both updating Dockerfile dependencies/plugin, code changes to use the gpu with the right elements, and testing

**Closed by frostbyte73** 2024-04-23 21:05 UTC
