### ISSUE TITLE
Negative duration in EgressInfo.File?

### ISSUE THREAD

**Issue by iAmcR** [livekit/egress#35] opened 2022-05-28 20:19 UTC
Looking at the below `EgressInfo` returned from a `egress_ended` event, the `duration` property seems to be consistently negative. It seems that it maybe for convenience where I'd have `start_time + (-1653767466240974001) == absolute_duration`, for example, but I'm not sure, as I'm used to a duration being positive number. Can you please clarify? 

```
file {
  filename: "video.mp4"
  size: 39657693
  location: "https://somewhere-out-there.mp4"
  duration: -1653767466240974001
}
```

**Comment by frostbyte73** [comment] 2022-05-31 23:00
It seems like that means your egress never started (it sets duration to endedAt - startedAt). Does the file exist?

**Comment by iAmcR** [comment] 2022-05-31 23:26
The egress definitely started and ended correctly, with the egress_ended event. Also the files do exist.

Another example is below with the startedAt and endedAt values, though I think those values are related to the start and stop times of the egress event itself, not the file's duration:

```
file {
  filename: "file_name_changed.mp4"
  size: 11990378
  location: "bucket_name_changed"
  duration: -1654038625305269137
}
started_at: 1654038625724565389
ended_at: 1654038656826047041 
```

The duration is always negative.  
(Just saw your edit)
There are no errors in EgressInfo. The Egress Type is Track Composite.

**Comment by frostbyte73** [comment] 2022-06-01 01:03
yeah, started_at and ended_at are the egress service not the actual file. I'm not able to reproduce this, but I'm adding some logs to help debug

**Comment by iAmcR** [comment] 2022-06-01 02:19
Thank you. I'll look out for it.

**Comment by frostbyte73** [comment] 2022-08-03 04:47
Closing as can't reproduce

**Closed by frostbyte73** 2022-08-03 04:47 UTC
